services:
  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VUE_APP_API_URL=http://localhost:5000
    depends_on:
      - backend
    command: npm run serve

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://postgres:password@database:5432/mydatabase
    depends_on:
      - database

  database:
    container_name: database
    build:
      context: .
      dockerfile: ./database/Dockerfile
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_database
    volumes:
      - ./database/db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
