# Use make scripts if you are running this app on UNIX environment
# Refer root: package.json if you are running on WINODWS environment
# Makefile for running Vue app development server

FRONTEND_DIR = frontend

# Default target to run the Vue app development server
app-start:
	cd $(FRONTEND_DIR) && \
	npm install && \
	npm run serve
